### ISSUE TITLE
Coordinates for stations

### ISSUE THREAD

**Issue by joanneroll** [stephan192/lhpapi#25]
### Is your feature request related to a problem? Please describe.

This client is really great for retrieving up to date information on the water gauges! Knowing the coordinates of all stations from the pegel.md would make this information even more usable in a spatial context.

### Describe the solution you'd like

 Is adding the coordinates something you plan for future developments?

**Comment by stephan192** [comment]
Hi @joanneroll, i do not have any plan to add this feature in future, due to more than one reason.
1. The effort is huge
2. The benefit for the typical user of this API is close to zero
3. Not all state portals offer coordinates and the API should be similar as possible for all states

**Comment by joanneroll** [comment]
Thanks for your clarification @stephan192, I do get your point(s)! For combining the water level information with other flood warnings, the geospatial information is quite nice. I already did this for the Bavarian state portal and was looking for a country wide solution. Regardless, this tool is really valuable since open data is hard to get by in this context^^
